#!/usr/bin/env python3
"""
Mermaidダイアグラムから HTMLファイルを生成するスクリプト
"""
import sys
from pathlib import Path

def generate_html(mermaid_file: Path, output_file: Path):
    """MermaidコードをHTMLファイルに変換"""

    # Mermaidファイルを読み込む
    with open(mermaid_file, 'r', encoding='utf-8') as f:
        mermaid_code = f.read()

    # HTMLテンプレート
    html_template = f"""<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SEO ETL Pipeline - データフロー図</title>
    <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f5f5f5;
        }}
        .container {{
            max-width: 1400px;
            margin: 0 auto;
            background: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }}
        h1 {{
            color: #333;
            border-bottom: 3px solid #01579b;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }}
        .description {{
            color: #666;
            margin-bottom: 30px;
            line-height: 1.6;
        }}
        .mermaid {{
            display: flex;
            justify-content: center;
            margin: 20px 0;
        }}
        .footer {{
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            color: #999;
            font-size: 0.9em;
            text-align: center;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>SEO ETL Pipeline - データフロー図</h1>
        <div class="description">
            <p>このプロジェクトのデータパイプライン全体像を示します。</p>
            <ul>
                <li><strong>データソース</strong>: Google Drive（生データ）、BigQuery（Search Console）</li>
                <li><strong>処理フロー</strong>: ダウンロード → マージ → 分析 → エクスポート → アップロード</li>
                <li><strong>保存先</strong>: Google Drive、Dify、GitHub</li>
            </ul>
        </div>
        <div class="mermaid">
{mermaid_code}
        </div>
        <div class="footer">
            Generated by SEO ETL Pipeline | 実行: <code>make diagram</code>
        </div>
    </div>
    <script>
        mermaid.initialize({{
            startOnLoad: true,
            theme: 'default',
            flowchart: {{
                useMaxWidth: true,
                htmlLabels: true,
                curve: 'basis'
            }}
        }});
    </script>
</body>
</html>
"""

    # HTMLファイルを書き込む
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(html_template)

    print(f"✓ ダイアグラムを生成しました: {output_file}")
    print(f"  ブラウザで開く: open {output_file}")

if __name__ == "__main__":
    # パスを設定
    project_root = Path(__file__).parent.parent
    mermaid_file = project_root / "docs" / "pipeline_diagram.mmd"
    output_file = project_root / "docs" / "pipeline_diagram.html"

    # ディレクトリが存在しない場合は作成
    output_file.parent.mkdir(parents=True, exist_ok=True)

    # HTML生成
    generate_html(mermaid_file, output_file)
